### ISSUE TITLE
可通过添加防火墙规则，禁用135，139访问

### ISSUE THREAD

**Issue by hcql** [WeiyiGeek/SecOpsDev#1]
可通过添加防火墙规则，禁用135，139访问
netsh advfirewall firewall add rule name="stop listening at TCP port 135，139" protocol=TCP dir=in localport=135,139 action=block enable=yes

发现脚本中已经有了。抱歉。

**Comment by WeiyiGeek** [comment]
New-NetFirewallRule -Name "CustomSecurity-Port" -DisplayName "CustomSecurity-Port" -Description "CustomSecurity-135-137-138-139-Port" -Direction Inbound -LocalPort 135,137,138,139 -Protocol TCP -Action Block -Enabled True
