### ISSUE TITLE
当有网卡禁用时，会报错。

### ISSUE THREAD

**Issue by broeeee** [WeiyiGeek/SecOpsDev#3]
当有网卡被禁用时，会报错，应该加个筛选Up状态的

$SysNetAdapter = @{}
function F_SysNetAdapter {
  $Adapter = Get-NetAdapter | Where-Object {$_.Status -eq "Up"} | Sort-Object -Property LinkSpeed
  foreach ( $Item in $Adapter) {
    $IPAddress = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $Item.ifIndex).IPAddress
    $SysNetAdapter += @{"$($Item.MacAddress)"="$($Item.Status) | $($Item.Name) | $($IPAddress) | $($Item.LinkSpeed) | $($Item.InterfaceDescription)"}
  }
  return $SysNetAdapter
}

**Comment by WeiyiGeek** [comment]
谢谢反馈，已修正该错误。

**Comment by WeiyiGeek** [comment]
> 当有网卡被禁用时，会报错，应该加个筛选Up状态的
> 
> $SysNetAdapter = @{} function F_SysNetAdapter { $Adapter = Get-NetAdapter | Where-Object {$_.Status -eq "Up"} | Sort-Object -Property LinkSpeed foreach ( $Item in $Adapter) { $IPAddress = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $Item.ifIndex).IPAddress $SysNetAdapter += @{"$($Item.MacAddress)"="$($Item.Status) | $($Item.Name) | $($IPAddress) | $($Item.LinkSpeed) | $($Item.InterfaceDescription)"} } return $SysNetAdapter }

谢谢反馈，已修正该错误，已提交到最新分支
