### ISSUE TITLE
关于文件获取后，中文注释乱码

### ISSUE THREAD

**Issue by linsihao7788** [WeiyiGeek/SecOpsDev#5]
大佬，我获取了windows的加固脚本 然后修改了一些地方再给到别人使用的时候中文都变成了乱码。直接就报错了

**Comment by WeiyiGeek** [comment]
请注意终端运行时的编码问题，其次是你保存脚本时是否是utf-8编码，如果是请将你终端编码也修改为utf-8，这样采用不会乱码。



个人博客: https://weiyigeek.top
来自 ***@***.*** 邮件通知
 
发件人： linsihao7788
发送时间： 2022-07-04 10:04
收件人： WeiyiGeek/SecOpsDev
抄送： Subscribed
主题： [WeiyiGeek/SecOpsDev] 关于文件获取后，中文注释乱码 (Issue #5)
大佬，我获取了windows的加固脚本 然后修改了一些地方再给到别人使用的时候中文都变成了乱码。直接就报错了
