### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by adminlove520** [WeiyiGeek/SecOpsDev#6]
这个咋恢复到原来的配置啊  网络出问题了

**Comment by adminlove520** [comment]
那个config.cfg.bak怎么用呀？想还原回去

**Comment by WeiyiGeek** [comment]
> 这个咋恢复到原来的配置啊 网络出问题了

你是网络配置不对还是其他出现问题呀？？？直接修改 /etc/netplan/00-installer-config.yaml 改回原IP和网络信息。

**Comment by WeiyiGeek** [comment]
> 那个config.cfg.bak怎么用呀？想还原回去

secedit /configure /db secconfig.sdb /cfg config.cfg.bak
